server:
  port: 8080

spring:
    application:
      name: SpringConfigClient
    cloud:
      config:
        uri: http://localhost:8888
        name: SpringConfigClient
        profile: profiles
        label: label
    profiles:
      active: profiles

