server:
  port: 8888

spring:
  config:
    name: configserver
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations:
            classpath:/test-config-repo/,
            classpath:/test-config-repo/{profile}/,
            classpath:/test-config-repo/{profile}/{label}/



