server:
  port: 8888

spring:
  config:
    name: configserver

# ${user.dir} points to the base directory you are running from.
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/SpringConfigServer/src/main/resources/test-git-repo


