spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations:
            classpath:/test-config-repo/{application},
            classpath:/test-config-repo/{application}/{profile}/{label},
            classpath:/test-config-repo/{profile}/{label}



